### ISSUE TITLE
Add nise.js as module entry point

### ISSUE THREAD

**Issue by griest024** [sinonjs/nise#10]
`import 'nise'` throws `Uncaught ReferenceError: global is not defined`.

**Comment by fatso83** [comment]
This description is way too brief. There is nothing showing that this is a problem. Can you point to a description somewhere where this is a problem, or give some reproducible way of establishing that the current way is not working?

**Comment by fatso83** [comment]
I think we can make a reproducible case if looking at [this comment](https://github.com/domenic/sinon-chai/pull/111#issuecomment-332672669) from domenic/sinon-chai#111.

**Comment by griest024** [comment]
Sorry for the short description. Basically, when the entry point is `lib/main.js`, I get a 
```
Uncaught ReferenceError: global is not defined
  at webpack:///~/nise/lib/fake-xhr/index.js:30:0
```

Unfortunately I can't exactly say what causes this, since its a dependency that is importing nise, I'm not using it directly.

**Comment by fatso83** [comment]
Ah, so it is a Webpack issue. That was the essential missing bit.

**Comment by griest024** [comment]
Since `module` isn't actually an npm option, I don't think it could break anything (famous last words) to add it to `package.json`. It does fix the issue though.

**Comment by griest024** [comment]
@fatso83 after more research, I found that this error is a result of calling `sinon.spy()`
