### ISSUE TITLE
FakeXHR and Event Targets

### ISSUE THREAD

**Issue by flatiron32** [sinonjs/nise#109]
The test below fails for me, but I think it should work. It is possible that i don't correctly understand what i am doing. 
I think that FakeXMLHttpRequest.dispatchEvent ought to set the target of the event, but it does not. 

```js
import { fakeXhr } from 'nise';

let xhrControl;
beforeEach(() => {
    xhrControl = fakeXhr.useFakeXMLHttpRequest();
});
afterEach(() => {
    xhrControl.restore();
});
test('Event target should be set', (done) => {
    const xhr = new XMLHttpRequest();
    xhr.addEventListener('error', (evt) => {
        expect(evt.target).toBe(xhr);
        done();
    }, false);
    const err = new ErrorEvent('error');
    xhr.dispatchEvent(err);
});
```

**Comment by fatso83** [comment]
Maybe you are able to dig up something a bit more definitive in the specs?  https://xhr.spec.whatwg.org/#event-handlers

**Comment by fatso83** [comment]
OK, looked into this, and while you are right about what it should do, to me it seems like it already does! Here is a full repro showing that the test does not fail: https://runkit.com/fatso83/nise-109

That is using JSDOM, mind you. Which browser are you seeing any errors in?

**Comment by fatso83** [comment]
These are the references I asked for, btw:
- 2.7 https://dom.spec.whatwg.org/#interface-eventtarget
- 2.9 https://dom.spec.whatwg.org/#dispatching-events

And they basically just verify what you said. `target` should be set.

**Comment by flatiron32** [comment]
This was in a unit test environment setup by jest with `testEnvironment: 'jest-environment-jsdom-global'` set. I would expect that to behave the same as your test. I might need to dig some more. Thank you.

**Comment by fatso83** [comment]
Jest is using JSDOM under the covers, AFAIK, so it _should_ do the same. I don't know if version differences should mean anything. Please report back if you do find out - bug or not :)
