### ISSUE TITLE
Rollup throws warnings about `nise` complaining the usage of `eval`

### ISSUE THREAD

**Issue by HarshaNalluru** [sinonjs/nise#110]
**Rollup bundler complains the usage of `eval` as it poses a security risk.** 
https://rollupjs.org/guide/en/#avoiding-eval

Screenshot of the error is as follows.
![image](https://user-images.githubusercontent.com/10452642/68241105-ef988800-ffc2-11e9-82cd-21d45f9a3d57.png)

**Related issues -**
ionic-team/ionic-app-scripts#129
https://github.com/ionic-team/ionic-cli/issues/1500
https://github.com/tus/tus-js-client/issues/147

**Comment by mantoni** [comment]
Lolex uses `eval` to execute something like `setTimeout('console.log("hi")', 100)`. However, this isn't valid in Node, and I tested Safari and Chrome and they fail with `Refused to execute a script because 'unsafe-eval' does not appear in the script-src directive of the Content Security Policy.`.

It seems to be a very old legacy feature and I vote for removing it.

**Comment by mroderick** [comment]
> It seems to be a very old legacy feature and I vote for removing it.

I think that's a good idea.

However, cutting that out is backwards incompatible and would trigger a major release.

Somewhere else, you suggested that we re-release `lolex` as `@sinonjs/clock`, which I am in favour of. We could make the change in a fresh major version released as the first version of `@sinonjs/clock`.

I think that adopting the new major version of `@sinonjs/clock` in `sinon` should also trigger a major version of `sinon`.

If you agree, let's create a issue in `lolex` for the renaming and track all the tasks to get that across the finish line in a good way.

**Comment by mantoni** [comment]
I agree 👍

**Comment by fatso83** [comment]
Moved to https://github.com/sinonjs/fake-timers/issues/319. Super easy fix for anyone that wants to contribute ...
