### ISSUE TITLE
TypeError: GlobalTextEncoder is not a constructor

### ISSUE THREAD

**Issue by itchyny** [sinonjs/nise#123]
We use sinon with [jsdom](https://github.com/jsdom/jsdom) and recently updated sinon to 8.0.1 and starts to fail with
```
        Mozilla/5.0 (darwin) AppleWebKit/537.36 (KHTML, like Gecko) jsdom/15.2.1
      Fake server request processing threw exception: GlobalTextEncoder is not a constructor
      TypeError: GlobalTextEncoder is not a constructor
          at convertToArrayBuffer (webpack:///./node_modules/nise/nise.js?:756:12)
          at convertResponseBody (webpack:///./node_modules/nise/nise.js?:960:30)
          at FakeXMLHttpRequest.setResponseBody (webpack:///./node_modules/nise/nise.js?:1317:29)
          at FakeXMLHttpRequest.respond (webpack:///./node_modules/nise/nise.js?:1333:18)
          at Object.processRequest (webpack:///./node_modules/nise/nise.js?:584:25)
          at eval (webpack:///./node_modules/nise/nise.js?:547:18)
          at Array.forEach (<anonymous>)
          at Object.respond (webpack:///./node_modules/nise/nise.js?:546:18)
```
jsdom does not implement TextEncoder ([ref](https://github.com/jsdom/jsdom/issues/2524)) and in ./node_modules/nise/nise.js `@sinonjs/text-encoding` is embed as empty module.

```
},{"./create-matcher":32,"./deep-equal":41,"./identical":43,"./is-arguments":44,"./is-element":46,"./is-map":47,"./is-neg-zero":49,"./is-set":51,"./match":54}],56:[function(require,module,exports){
  // empty!
},{}],57:[function(require,module,exports){

// abbrev...

module.exports = extend(fakeXMLHttpRequestFor(globalObject), {
    fakeXMLHttpRequestFor: fakeXMLHttpRequestFor
});

},{"../configure-logger":1,"../event":5,"./blob":10,"@sinonjs/commons":19,"@sinonjs/text-encoding":56,"just-extend":58}],12:[function(require,module,exports){ // the number is 56
```

I expect nise loads sinonjs/text-encoding properly. How can I use sinon with jsdom?

**Comment by itchyny** [comment]
For comparison, when I use sinon 7.5.0 (with nise 1.5.2), `sinonjs/text-encoding` is apparently not empty 
```
}).call(this,typeof global !== "undefined" ? global : typeof self !== "undefined" ? self : typeof window !== "undefined" ? window : {})
},{"../configure-logger":1,"../event":5,"./blob":10,"@sinonjs/text-encoding":46,"just-extend":50}],12:[function(require,module,exports){
// the package number is 46
```
```
},{"./deep-equal":29,"./identical":32,"./is-arguments":33,"./is-element":35,"./is-neg-zero":38,"./is-set":40,"./match":43,"./matcher":44}],46:[function(require,module,exports){
// This is free and unencumbered software released into the public domain.
// See LICENSE.md for more information.

var encoding = require("./lib/encoding.js");

module.exports = {
  TextEncoder: encoding.TextEncoder,
  TextDecoder: encoding.TextDecoder,
};

},{"./lib/encoding.js":48}],47:[function(require,module,exports){
(function(global) {
```
I suspect the browser key in package.json but I have no clue why it is related.

**Comment by mroderick** [comment]
@mantoni could this be caused by something exotic in the browserify setup in Sinon?

**Comment by mantoni** [comment]
Yes, I'm pretty sure this is caused by the `browser` key in `package.json`:

https://github.com/sinonjs/nise/blob/76fe10ccd3dc867f03ce942d1e5a8c72822003e8/package.json#L28-L32

I introduced it [in this PR](https://github.com/sinonjs/nise/commit/0a81369a9283c28fd9392a5ce4b88b1ca6e2d38c) assuming that all browsers implement it. I wasn't aware that JSDom doesn't support it.

We feature detect support for `TextEncoding` here already:

https://github.com/sinonjs/nise/blob/76fe10ccd3dc867f03ce942d1e5a8c72822003e8/lib/fake-xhr/index.js#L3-L5

The browserify config causes the `@sinonjs/text-encoding` module to be replaced with an empty object, therefore the exception.

The simple fix is to remove the one line from the `browser` config. I'll send a PR.

**Comment by itchyny** [comment]
I confirmed the fix in our project. Thank you.
