### ISSUE TITLE
`readystatechange` event should not be triggered after `loadend`

### ISSUE THREAD

**Issue by carlisliu** [sinonjs/nise#165]
```
var xhr = new nise.fakeXhr.FakeXMLHttpRequest();
xhr.addEventListener('readystatechange', ()=>{
    console.log(performance.now(), 'readystatechange');
});
xhr.addEventListener('loadend', ()=>{
    console.log(performance.now(), 'loadend');
});
xhr.open('GET', '/');
xhr.send();

xhr.respond(200);
```
output:
![image](https://user-images.githubusercontent.com/2157653/84789441-d1980900-b022-11ea-97a6-2bf65bb875fa.png)

when using stardard XMLHttpRequest the same way
```
var xhr = new XMLHttpRequest();
xhr.addEventListener('readystatechange', ()=>{
    console.log(performance.now(), 'readystatechange');
});
xhr.addEventListener('loadend', ()=>{
    console.log(performance.now(), 'loadend');
});
xhr.open('GET', 'https://github.com/sinonjs/nise');
xhr.send();
```

output:
![image](https://user-images.githubusercontent.com/2157653/84789639-0b690f80-b023-11ea-8703-83f5225f5262.png)

this is imcompatible with some network lib(like [`natty-fetch`](https://www.npmjs.com/package/natty-fetch))

**Comment by codejedi365** [comment]
I believe I have isolated where this issue occurs during my investigation detailed in my PR #183.  My PR does not resolve this issue but was a side effect related to this issue.  The `respond()` function of `nise/lib/fake-xhr/index.js` line 799 provides a few function calls which call `this.setResponseBody()` and `setResponseBody()` is the culprit who dispatches the last readystatechange event after detecting a state of `FakeXMLHttpRequest.DONE`.

Working on a fix...
