### ISSUE TITLE
text-encoding dependency is not available anymore

### ISSUE THREAD

**Issue by mhterres** [sinonjs/nise#169]
Hello.

wget https://registry.npmjs.org/@sinonjs/text-encoding/-/text-encoding-0.7.1.tgz
--2020-08-06 11:16:05--  https://registry.npmjs.org/@sinonjs/text-encoding/-/text-encoding-0.7.1.tgz
Resolving registry.npmjs.org (registry.npmjs.org)... 104.16.23.35, 104.16.17.35, 104.16.22.35, ...
Connecting to registry.npmjs.org (registry.npmjs.org)|104.16.23.35|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2020-08-06 11:16:05 ERROR 404: Not Found.

npm i @sinonjs/text-encoding
npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/@sinonjs%2ftext-encoding - Not found
npm ERR! 404 
npm ERR! 404  '@sinonjs/text-encoding@latest' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

**Comment by mantoni** [comment]
Apparently an npm glitch. The files are loading fine again.
