### ISSUE TITLE
Does not work with latest version of `just-extend`

### ISSUE THREAD

**Issue by maoberlehner** [sinonjs/nise#17]
This change: https://github.com/angus-c/just/commit/886a4ff3dd77bb61695dc982e98533f6ae1e19a1#diff-3333af3f3ec7ec75ad2ea0a69dc86bbbR38 breaks this https://github.com/sinonjs/nise/blob/master/lib/fake-xhr/index.js#L651

As far as I can see, it is not possible anymore to use `extend()` with a function as its first parameter.

**Comment by panitaxx** [comment]
If you use yarn add the following line for a quick fix:

"resolutions": {
    "**/nise/just-extend": "1.1.22"
  }

That will pin the version to 1.1.22. Don't know if it works on npm.
