### ISSUE TITLE
The same handler registered twice with addEventListener should be discarded

### ISSUE THREAD

**Issue by betalb** [sinonjs/nise#19]
According to documentation from MDN https://developer.mozilla.org/en-US/docs/Web/API/EventTarget/addEventListener, if listener is registered more than once it should be discarded. I haven't found any specific details on how to translate `with the same parameters` in regards to XHR. Event type and listener are definitely part of this, and seems that `options.once` should be added to equality comparison, as it works as expected for XHR.

**Comment by betalb** [comment]
I think that this issue is still there, I see that `addEventListener` implementation in https://github.com/sinonjs/nise/blob/master/lib/event/event-target.js just pushes new listener to the list without checking it's presense

**Comment by mroderick** [comment]
Let's pin this for awhile, and see if it can attract some attention. Pull requests welcome

**Comment by mroderick** [comment]
This has been fixed in #31 and published as `nise@1.2.5`. I am closing this issue.

If you want to work on `options.once`, please create a new issue for that.

Thanks
