### ISSUE TITLE
respondWith with a function

### ISSUE THREAD

**Issue by elijahiuu** [sinonjs/nise#20]
I tried passing a function into server.respondWith() but i think there is a bug in processing response results.

here's my call:

```
var server = sinon.fakeServer.create();
server.respondWith("POST", "/foo/api", function(request) {
   var req = JSON.parse(request.requestBody);
   return [200, {"Content-Type": "application/json"},JSON.stringify({ req.bar === 'hello world' ? 'yes' : 'no'})}];
});
```

The problem seems to be here:
node_modules/nise/lib/fake-server/index.js:261
`request.respond(response[0], response[1], response[2]);`

Instead it should do something like this: 
```
if (typeof response.response === "function") {
  response = response();
} 
return request.respond(response[0], response[1], response[2]);
```

**Comment by fatso83** [comment]
Can you make a failing test that will pass if it is correct? It seems weird if this core functionality should suddenly break, so I suspect wrong usage. [From the docs](https://github.com/sinonjs/nise#serverrespondwithurlregexp-response):

> If the response is a Function, it will be passed any capture groups from the regular expression along with the XMLHttpRequest object:
```javascript
server.respondWith(/\/todo-items\/(\d+)/, function (xhr, id) {
    xhr.respond(200, { "Content-Type": "application/json" }, '[{ "id": ' + id + " }]");
});
```
