### ISSUE TITLE
Document legacyRoutes flag and make it disabled by default

### ISSUE THREAD

**Issue by fatso83** [sinonjs/nise#224]
PR #223 introduced the legacyRoutes flag and set it to be enabled by default to ensure the previous behavior was kept. To enable the new features in the underlying lib, we should consider enabling it by default, but this requires updating docs in Nise first in any case.

**Comment by fatso83** [comment]
@43081j Does this option make any sense anymore, now that the underlying library has changed its syntax yet again, so that `?` no longer has special meaning? I think not, so I'd roll the feature back before the next major.

Ref #226 and #223

**Comment by 43081j** [comment]
Ah interesting! They made another breaking change I see 😅

You're probably right and we can drop this option since `?` has no special meaning anymore
