### ISSUE TITLE
Add support for ResponseCache API

### ISSUE THREAD

**Issue by fatso83** [sinonjs/nise#232]
There was [a question on why setting the `cache` property on the request was not visible](https://github.com/sinonjs/nise/discussions/231). The simple reason is that there is no support added for the [ResponseCache API](https://developer.mozilla.org/en-US/docs/Web/API/Request/cache). Adding it seems simple enough, but someone needs to do it 🥇

**Comment by HarelM** [comment]
I'll see if I can look into it, any pointers on how to get started with this repo?
It was a long time ago that I opened the initial issue, so I need to remember what I tried there, although the code I wrote is fairly good in defining the problem.

**Comment by fatso83** [comment]
- Use the major version of Node in .tool-versions (16)
- `npm i && npm test -- --watch`

The test suite is fast and quite comprehensive and should tell you if something is off. Apart from that ... 🤷

**Comment by HarelM** [comment]
Actually, I can't find `cache` parameter in `XMLHttpRequest` API, so it might be only relevant to `fetch` request, which is not supported by this library, right?
