### ISSUE TITLE
XHR.timeout not implemented.

### ISSUE THREAD

**Issue by Munksey** [sinonjs/nise#3]
There was a ticket on sinon from a while back: https://github.com/sinonjs/sinon/issues/431. I attempted to fix this with the following PR: https://github.com/sinonjs/sinon/pull/1495/files.

It'd be pretty easy for me to port the PR, since the files haven't changed much.

My thought was to only set the timeout functionality if an instance of global XMLHttpRequest has the timeout variable and if `send` is called while fake timers are activated. I've taken into account quirks like `fakeServerWithClocks` forcing a tick for the longest timeout.

If this sounds reason let me know and I would be happy to create a PR for review.

**Comment by mroderick** [comment]
That would be a most welcome contribution 💯

**Comment by lexatnet** [comment]
+1
