### ISSUE TITLE
Proposal: remove `text-encoding` dependency

### ISSUE THREAD

**Issue by maoberlehner** [sinonjs/nise#44]
Although this package is most likely only rarely used in the browser, and it is (hopefully) never used on a live site, I'm still concerned by the huge overhead the `text-encoding` dependency adds. The package size is about 500kb with `text-encoding` and 40kb without.

I'm using this package to fake XHR requests in automated acceptance tests with Nightwatch.js and although loading is not too much of an issue when the file isn't sent over the network, parsing it in the browser is a significant burden on the performance of the test system.

As a quick workaround, I've just forked this package and removed everything `text-encoding` related (https://github.com/maoberlehner/nise/commit/64db34ea3f76b876193ac5ba7386384cfb0cd2f8).

Is there any chance to get rid of this dependency? Maybe it is possible to make it optional, so people who actually need ArrayBuffers and Blobs, can add it manually?

**Comment by mroderick** [comment]
Thank you for your contribution!

`text-encoding` is indeed a heavy dependency. If we can reduce the amount of data that needs to be transferred and parsed, without causing problems for users, then everyone wins 🚀 

Have you done any measurements of the impact using your fork has, over the unmodified `nise`?

> Is there any chance to get rid of this dependency? Maybe it is possible to make it optional, so people who actually need ArrayBuffers and Blobs, can add it manually?

Suggestions on how to make this happen would be most welcome
