### ISSUE TITLE
unable to install nise version 1.4.4

### ISSUE THREAD

**Issue by arankhem** [sinonjs/nise#64]
When i am trying to install nise version 1.4.4 i am getting the below error
**Tried commands**
npm install -g nise
npm install -g nise@1.4.4

**Error**
npm ERR! code ETARGET
npm ERR! notarget No matching version found for just-extend@^3.0.0
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
npm ERR! notarget

But when i am trying to install nise version 1.4.3 then it doesnt throw any error

npm install -g  nise@1.4.3
+ nise@1.4.3
updated 1 package in 11.051s

**Comment by arankhem** [comment]
@mroderick, can you help here please

**Comment by mroderick** [comment]
Please see my response to the other issue you created: https://github.com/sinonjs/sinon/issues/1894#issuecomment-419009779

**Comment by fatso83** [comment]
Like Morgan said elsewhere, please don't ping people for stuff like this. It's demanding and not welcome. We see the issues as they come in, and unless you are explicitly paying us per the hour, you can fix stuff yourself and send us the PR.

Just extend was [released in version 3 over three weeks ago](https://www.npmjs.com/package/just-extend) (you can also see our changelog). You could also do the check from your CLI:

```
$ npm show just-extend

just-extend@3.0.0 | MIT | deps: none | versions: 23
extend an object
https://github.com/angus-c/just#readme

keywords: object, assign, clone, copy, merge, deep-copy, extend, no-dependencies, just

dist
.tarball: https://registry.npmjs.org/just-extend/-/just-extend-3.0.0.tgz
.shasum: cee004031eaabf6406da03a7b84e4fe9d78ef288
.integrity: sha512-Fu3T6pKBuxjWT/p4DkqGHFRsysc8OauWr4ZRTY9dIx07Y9O0RkoR5jcv28aeD1vuAwhm3nLkDurwLXoALp4DpQ==
.unpackedSize: 4.2 kB

maintainers:
- angus-c <anguscroll@gmail.com>

dist-tags:
latest: 3.0.0  

published 3 weeks ago by angus-c <anguscroll@gmail.com>
```

Also, I was unable to reproduce this. I tried both a local install and a global install (no idea what you want to do with a global install, though ...). Strongly suspecting user foul.

**Comment by arankhem** [comment]
ok sorry for that..
