### ISSUE TITLE
FakeServer can't support fetch api

### ISSUE THREAD

**Issue by loliconer** [sinonjs/nise#7]
When using fetch api to request a url, the fake server can't match the url and the browser returns 404

**Comment by fatso83** [comment]
You can use an existing library, like [fake-fetch](https://www.npmjs.com/package/fake-fetch), or you can provide this project with a pull request that adds the functionality :smiley:

**Comment by loliconer** [comment]
Thanks! Now that there is already a library that supports Fetch, it's not so necessary to add it here, though it is better to have the functionality.
