### ISSUE TITLE
Bind to different Window context?

### ISSUE THREAD

**Issue by timpur** [sinonjs/nise#70]
Wondering if it is posable to bind this library to use a different window / global context programatically ?

Experimenting with PollyJs and CypressJs. Need to bind this lib to a different window to get this to work. 

Happy to fo the work needed, just wondering if this is something this lib will embrace? 

Thx

**Comment by mroderick** [comment]
The description doesn't give much detail. What do you want to accomplish, that is not currently possible?

**Comment by timpur** [comment]
@mroderick, any questions?

**Comment by timpur** [comment]
Yeah, it makes sense that you can pick which window you bind to, especially in a testing use case like mine :), Thanks @mroderick.

So if i create a pr related to this you guys would be interested ?

**Comment by mroderick** [comment]
Absolutely 👍

**Comment by timpur** [comment]
hmm never got around to doing coding this up ...

**Comment by mroderick** [comment]
> hmm never got around to doing coding this up ...

There's still time :)
