### ISSUE TITLE
Out of Date dependencies.

### ISSUE THREAD

**Issue by intervalia** [sinonjs/nise#73]
Can you please update all of your dependencies to resolve some security issues?

* just-extend should go from 3.0.0 to 4.0.2
* lolex should go from 2.7.5 to 3.0.0
* path-to-regexp should go from 1.7.0 to the latest 2.4.0
* text-encoding should be completely replaced or, at least, be moved from 0.6.4 to 0.7.0

**Comment by mroderick** [comment]
There are no known vulnerabilities in the dependencies that are installed with with current version.

**Comment by intervalia** [comment]
`text-encoding` is deprecated

**Comment by mroderick** [comment]
> `text-encoding` is deprecated

It still does the job and has no security warnings against it. Do you know of any other packages that polyfill the missing APIs?
