### ISSUE TITLE
General question: Nise vs Sinon.JS fakeserver

### ISSUE THREAD

**Issue by flovogt** [sinonjs/nise#75]
Hi team,
I've some general questions to this project which I can not answer by the documentation.
What is the way to go to use fakeServer in a JS project. Should I use sinon.js fakeserver or nise?
Is there a future roadmap to remove fakeServer from Sinon.js?
Thanks a lot for your work! FakeServer helped me so lot.

**Comment by mantoni** [comment]
Sinon.JS will always be the “full package”. We started an effort to modularize Sinon in case you don’t want to use everything. For example, other test frameworks can use only the fake timers (lolex) or only the fake server (nise). There are no plans to remove these modules from Sinon.

**Comment by flovogt** [comment]
Thanks a lot for this clarification. Would be nice to have this poitn mentioned in the readme or in the documentation.

**Comment by mroderick** [comment]
> Thanks a lot for this clarification. Would be nice to have this poitn mentioned in the readme or in the documentation.

Thank you for your feedback. All the `@sinonjs/*` projects are run by volunteers and rely on contributions from the community to move things forwards. Would you like to contribute a pull request to the README / documentation to make this clearer?
