### ISSUE TITLE
Default route matched in addition to more specific route

### ISSUE THREAD

**Issue by fatso83** [sinonjs/nise#8]
Moved from sinonjs/sinon#1528.

Running the test case where only the `/foo` route should be matched results in both being matched. To reproduce:

```
$ npm i -g phantomic phantomjs-prebuilt browserify 
$ npm i babelify babel-preset-es2015 

$ browserify test.js  -t [ babelify --presets [ es2015  ] ] -o bundle.js && phantomic bundle.js
requesting foo
foo requested
default requested
INVALID_STATE_ERR - 4 Error: INVALID_STATE_ERR - 4
status == 200? true
```

<details>
<summary>test.js</summary>

```javascript
// when testing locally in the repo: const nise = require('./lib/')
const nise = require('nise');

const server = nise.fakeServer.create();

// each response should be triggered exactly once
let fooResponded = false;
let defaultResponded = false;

// default responder
server.respondWith(xhr=>{
    console.log('default requested')
    if (defaultResponded)
        console.log("default requested more than once!");
    defaultResponded = true;
    try {
    xhr.respond(404, {}, '');
    }catch(err) {
        console.log(err);
    }
});

// foo responder
server.respondWith('/foo', xhr=>{
    console.log('foo requested')
    if (fooResponded)
        console.log("foo requested more than once!");
    fooResponded = true;
    return xhr.respond(200, {}, '');
});


// request foo
let r = new XMLHttpRequest();
console.log('requesting foo');
r.open('GET', '/foo', false);
r.send();
console.log('status == 200?', r.status === 200);
```

</details>

**Comment by fatso83** [comment]
This error has been around since the very start. It has been verified to exist in Sinon 1.4 - 5 years ago.

**Comment by fatso83** [comment]
You should follow this issue, @n1ywb. If you have any possibility to dive into this, feel free to do so, as none of the maintainers of the main sinon package uses this functionality all that much. All you need to do is look through how requests are being matched. I am guessing the fix is not all that hard (famous last words) :stuck_out_tongue:

**Comment by rgroothuijsen** [comment]
Did a bit of testing in regards to this one, and initially thought that the cause was less specific routes being matched. However, if you change the default route to "/" for example, it doesn't happen. It's specific to the default responder, which has a null response URL, and in this case the code always returns that it's a match and calls the response. Normally the response list loop would stop after the first match it finds, but this responder doesn't return a proper reply, and so the loop keeps going.

**Comment by fatso83** [comment]
@rgroothuijsen, as you can see from [the history in the Sinon repo](https://github.com/sinonjs/sinon/blob/v1.17/lib/sinon/util/fake_server.js), most stuff involving the fake server has been done by other people than the current maintainers (originally @cjohansen), so it's hard to guess at design decision without digging properly into `git blame`, commit messages and discussions on the pull requests. 

Glancing at [the code](https://github.com/sinonjs/nise/blob/master/lib/fake-server/index.js) I was unable to find the bit you referred to as "evaluating the response", but in any case; feel free to poke around and see if you can get a meaningful fix in. I am unsure if we are able to help you with the background of the implementation details, unfortunately.

**Comment by rgroothuijsen** [comment]
I see, I might look into that sometime then. For the record, the "evaluating the response" part I was referring to was [this line](https://github.com/sinonjs/nise/blob/master/lib/fake-server/index.js#L79), which confused me a bit as the match() function can apparently return either true, false, or a response object.

**Comment by n1ywb** [comment]
closing bug tickets automatically is a great way to ensure that bugs are never fixed

**Comment by mantoni** [comment]
@n1ywb It's also a great way to make sure the issue tracker is relevant. We know that this comes at the price of actual issues not being fixed. If you want to help out and send a PR for this, we're still up for merging. If you have more information to provide to help somebody else fix it, we can reopen. Thank you for your help and understanding.

**Comment by mpaluchowski** [comment]
The short answer to the original issue from @fatso83 is, the code will behave as you expect if you write the "foo responder" as:

```javascript
// foo responder
server.respondWith('/foo', xhr=>{
    console.log('foo requested')
    if (fooResponded)
        console.log("foo requested more than once!");
    fooResponded = true;
    xhr.respond(200, {}, '');
    return true;
});
```

Notice I added an explicit `return true;` in the end. The thing is, the `xhr.respond(...)` function doesn't return anything. See `/lib/fake-server/index.js`, line 227. This means your `respondWith` callback doesn't return anything, effectively it's a void function. Line 79 interprets this as `false` and treats the request as though it wasn't handled.

From what I can tell, the original decision for the `respondWith` callbacks was that they should return a boolean, informing whether the specific request was handled or not. If they return anything falsy, including void, then request processing continues.

One solution would be to make these assumptions explicit in documentation and possibly have the code report an error if the callback function doesn't return an explicit boolean value.
