### ISSUE TITLE
Configure greenkeeper to keep deps up to date

### ISSUE THREAD

**Issue by JustinBeckwith** [sinonjs/nise#81]
This repository has a lot of old deps, with many security vulnz.  It would be great to install [greenkeeper](https://greenkeeper.io/) so we get PRs with updates.  If you'd like getting this rolling - I'm interested in helping as a maintainer of the lib.

**Comment by JustinBeckwith** [comment]
Greetings!  Gentle ping :)

**Comment by fatso83** [comment]
I wouldn't worry to much about the perceived security threat of a test library, but its of course good to get rid of the `npm audit` noise. That being said, I remember using Greenkeeper on other Sinon projects (are we still?) and I thought it was a lot of noise for little gain.

**Comment by fatso83** [comment]
@JustinBeckwith Sorry to keep you hanging - I kind of forgot about the second part of your question, concerning maintaining. The maintainer part also concerns looking into issues, answering questions - sending people over to StackOverflow if it's not a bug, reviewing PRs, etc., not just keeping dependencies up to date :-) Would you be interested in donating some time to that?

**Comment by fatso83** [comment]
Greenkeeper is fine, btw, but as you can tell, we are kind of swamped on time, so more pings about not-that-important Greenkeeper updates isn't always what we crave for. But if someone can tend to the baby, then it's another matter.

**Comment by mantoni** [comment]
I have activated automatic security fixes on GitHub for this repo. Should be less noisy since it’s „only“ about security issues.

**Comment by fatso83** [comment]
@mantoni Using Greenkeeper or something else? And some time ago or just now? Because there were some audits in the "High" risk category.

**Comment by mantoni** [comment]
Just now, not Greenkeeper, but the new GitHub feature. I enabled it on the Sinon project as well last week.

**Comment by JustinBeckwith** [comment]
@fatso83 awesome!  I'd be more than happy to help with the other maintainy bits as well.  We use this and sinon all over the place, so we may as well do our part :)
