### ISSUE TITLE
Error: Cannot find module 'text-encoding'

### ISSUE THREAD

**Issue by damien-gl** [sinonjs/nise#83]
Hello,

Since the latest release `1.4.9` I'm getting the following error:
```
Error: Cannot find module 'text-encoding'
```

Apparently the fix is already committed but not yet released:
https://github.com/sinonjs/nise/commit/fb3b595c0bd5b9ef8282c156f3320b2b345cd918

Any plan to release it quickly?
Many thanks!

**Comment by fatso83** [comment]
This was pushed a bit before your issue, as 1.4.10
