### ISSUE TITLE
readystatechange OPENED event triggered on send()

### ISSUE THREAD

**Issue by tym-network** [sinonjs/nise#89]
Hi there!

I noticed that nise is sending the readystatechange event with an "OPENED" readystate when calling the `xhr.send()` function, while the native XHR doesn't.

As it's pretty hard to explain, here is an example of what the native XHR triggers and what nise does: https://jsfiddle.net/1djoqatw/2/

We can see that nise triggers an "OPENED" event for both `xhr.open()` and `xhr.send()`, while the native XHR only triggers it once when `xhr.open()` is being called.

It's pretty problematic for us as we are doing some actions on the readystatechange event listener which gets called too many times in our unit tests.

Is there a particular reason for "OPENED" to be triggered when `send()` is called?

Thank you very much,

Have a nice day!

**Comment by fatso83** [comment]
I remember @fearphage doing a lot of nitty-gritty detailed XHR compliancy work some time ago. He might know. But we are all volunteering our time, so you might have better luck (or a faster path to the answer) by doing some code archeology on the code in question, along with the tests for that feature:
- use Git blame on the file
- if a newer commit hides the original change, go the the parent and view the blame output for that
- if you get all the way back to the original commit where lolex was forked out from the Sinon core, you might want to investigate further in older Sinon commits ...

I've done this from time to time, and while time consuming, it brings results.

On the other hand, it might not be a "feature" that was put there intentionally. I see that this behaviour isn't covered by [our tests](https://github.com/sinonjs/nise/blob/master/lib/fake-xhr/index.test.js) for the XHR module, so it might just be a side effect of sharing code paths between `open` and `send` ...

**Comment by fatso83** [comment]
Relevant reading:
- https://xhr.spec.whatwg.org/#the-open()-method
- https://xhr.spec.whatwg.org/#the-send()-method

You might discover that we do what's right - or possibly not :)

**Comment by tym-network** [comment]
Thank you @fatso83 for your blazing fast answer!

So I digged a bit into the code as you told me and I had the pleasure to travel in time through the git history :)
It looks like the "OPENED" readystatechange in `send()` has been there since the first implementation of XHR in Sinon (May 2010). Here's the commit linked to it: https://github.com/sinonjs/sinon/commit/6ebef56dc87f5a252d445965a4f8e81d5c999e80
It has never been removed since then.

I guess this has never really been a subject of discussion and is probably part of the "history" now.


Based on the two links you provided, I believe that triggering an "opened" readystatechange to in `send()` doesn't make much sense if you follow the specs.

1. The definition of the `opened` readystate is pretty explicit (from https://xhr.spec.whatwg.org/#states)
> The open() method has been successfully invoked. During this state request headers can be set using setRequestHeader() and the fetch can be initiated using the send() method.

2. They mention that `send()` can't be called unless the ready state is `opened`:
> If state is not opened, then throw an "InvalidStateError" DOMException.

3. They never mention the fact that the `send()` method should `Set state to opened`, unlike the `open()` function. 


I believe that removing the "opened" readystatechange trigger from the `send()` method would better match the specifications as well as the actual implementations of xhr in the browsers.

What do you think?

Have a great day

**Comment by fatso83** [comment]
Seems like a very well researched proposal! Looks like the right change to me, although I'm no expert, so if anyone would supply a PR it has a pretty good chance of being part of a next major release ;-)

**Comment by fearphage** [comment]
The problem may be able to be simplified into we're firing `readystateCHANGE` events when the ready state has in fact **not** changed. I'm able to replicate this from the test case above.

I believe I've fixed this before (in SInon). I'll investigate.

**Comment by fatso83** [comment]
@fearphage Did you get anywhere in your investigation?

**Comment by mroderick** [comment]
This has been fixed in `nise@1.5.2`
